using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Web.Script.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using System.Windows.Interop;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Threading;
using Forms=System.Windows.Forms;
using Drawing=System.Drawing;

[assembly:AssemblyTitle("桌面日程")]
[assembly:AssemblyDescription("原生 Windows 桌面日程与待办小组件")]
[assembly:AssemblyProduct("桌面日程")]
[assembly:AssemblyVersion("2.3.0.0")]
[assembly:AssemblyFileVersion("2.3.0.0")]

public sealed class TaskItem:INotifyPropertyChanged
{
 string id,title,dueDate,dueTime,category,repeat,location,notes,notified;bool isDone,recurrenceCreated;int reminder;
 public TaskItem(){id=Guid.NewGuid().ToString();title="";dueDate=DateTime.Today.ToString("yyyy-MM-dd");dueTime="";category="个人";repeat="不重复";location=notes=notified="";reminder=-1;}
 public string Id{get{return id;}set{Set(ref id,value);}}public string Title{get{return title;}set{Set(ref title,value??"");}}public bool IsDone{get{return isDone;}set{Set(ref isDone,value);}}
 public string DueDate{get{return dueDate;}set{Set(ref dueDate,value??"");Notify("Meta");}}public string DueTime{get{return dueTime;}set{Set(ref dueTime,value??"");Notify("Meta");}}
 public string Category{get{return category;}set{Set(ref category,value??"个人");Notify("Meta");Notify("CategoryBrush");}}public string Repeat{get{return repeat;}set{Set(ref repeat,value??"不重复");Notify("Meta");}}
 public int Reminder{get{return reminder;}set{Set(ref reminder,value);}}public string Location{get{return location;}set{Set(ref location,value??"");Notify("Meta");}}public string Notes{get{return notes;}set{Set(ref notes,value??"");}}
 public string Notified{get{return notified;}set{Set(ref notified,value??"");}}public bool RecurrenceCreated{get{return recurrenceCreated;}set{Set(ref recurrenceCreated,value);}}
 [ScriptIgnore]public Brush CategoryBrush{get{string c=Category=="工作"?"#607FF2":Category=="生活"?"#46B58B":Category=="重要"?"#F06D6D":"#A77BE8";return new SolidColorBrush((Color)ColorConverter.ConvertFromString(c));}}
 [ScriptIgnore]public string Meta{get{var p=new List<string>();DateTime d;if(DateTime.TryParseExact(DueDate,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out d))p.Add(d.ToString("M月d日 ddd",CultureInfo.GetCultureInfo("zh-CN")));if(!String.IsNullOrEmpty(DueTime))p.Add(DueTime);if(!String.IsNullOrEmpty(Category))p.Add(Category);if(!String.IsNullOrEmpty(Location))p.Add(Location);if(!String.IsNullOrEmpty(Repeat)&&Repeat!="不重复")p.Add(Repeat);return String.Join(" · ",p);}}
 public event PropertyChangedEventHandler PropertyChanged;void Notify(string n){var h=PropertyChanged;if(h!=null)h(this,new PropertyChangedEventArgs(n));}void Set<T>(ref T f,T v,[CallerMemberName]string n=null){if(EqualityComparer<T>.Default.Equals(f,v))return;f=v;Notify(n);}
}
public sealed class WindowSettings{public double Left{get;set;}public double Top{get;set;}public double Width{get;set;}public double Height{get;set;}public bool Topmost{get;set;}public string Theme{get;set;}public double Opacity{get;set;}}
public sealed class DayEntry{public string Display{get;set;}public TaskItem Task{get;set;}}

internal sealed class DesktopTodoApp
{
 readonly string folder,taskPath,settingsPath,logPath;readonly JavaScriptSerializer json=new JavaScriptSerializer();readonly bool selfTest;
 Window window;ObservableCollection<TaskItem> tasks;ICollectionView view;string mode="Agenda";bool loading,editing;TaskItem editingTask;
 Forms.NotifyIcon notifyIcon;DispatcherTimer reminderTimer,settingsTimer;
 Grid agendaPanel,calendarPanel;Border editorPanel,detailsPanel,settingsPanel;ListBox taskList,dayList;TextBox searchBox,editTitle,editLocation,editNotes;TextBlock searchHint,headerTitle,emptyTitle,countText,opacityValue,detailTitle,detailStatus,detailDateTime,detailCategoryRepeat,detailReminder,detailLocation,detailNotes;StackPanel emptyState;Slider opacitySlider;TaskItem detailsTask;
 System.Windows.Controls.Calendar monthCalendar;DatePicker editDate;ComboBox editHour,editMinute,editCategory,editRepeat,editReminder,themeSelect;Button agendaTab,todayTab,calendarTab,completedTab,pinButton;
 public DesktopTodoApp(bool test){selfTest=test;folder=AppDomain.CurrentDomain.BaseDirectory;taskPath=Path.Combine(folder,"tasks.json");settingsPath=Path.Combine(folder,"widget-settings.json");logPath=Path.Combine(folder,"桌面日程-错误日志.txt");}
 T Find<T>(string n)where T:class{T v=window.FindName(n)as T;if(v==null)throw new InvalidOperationException("找不到控件："+n);return v;}
 public void Run(){using(Stream s=Assembly.GetExecutingAssembly().GetManifestResourceStream("UI.xaml")){if(s==null)throw new InvalidOperationException("找不到 UI.xaml");window=(Window)XamlReader.Load(s);}Resolve();LoadSettings();LoadTasks();Bind();Wire();StartNotifications();UpdateTabs();RefreshDay();UpdateSummary();if(selfTest)window.ContentRendered+=RunSelfTest;var app=new Application{ShutdownMode=ShutdownMode.OnMainWindowClose};app.DispatcherUnhandledException+=delegate(object o,DispatcherUnhandledExceptionEventArgs e){Log(e.Exception);e.Handled=true;MessageBox.Show("操作失败，程序已保护性恢复。详情见错误日志。","桌面日程");};app.Run(window);}
 void Resolve(){agendaPanel=Find<Grid>("AgendaPanel");calendarPanel=Find<Grid>("CalendarPanel");editorPanel=Find<Border>("EditorPanel");detailsPanel=Find<Border>("DetailsPanel");settingsPanel=Find<Border>("SettingsPanel");taskList=Find<ListBox>("TaskList");dayList=Find<ListBox>("DayList");searchBox=Find<TextBox>("SearchBox");searchHint=Find<TextBlock>("SearchHint");headerTitle=Find<TextBlock>("HeaderTitle");emptyTitle=Find<TextBlock>("EmptyTitle");countText=Find<TextBlock>("CountText");emptyState=Find<StackPanel>("EmptyState");monthCalendar=Find<System.Windows.Controls.Calendar>("MonthCalendar");editDate=Find<DatePicker>("EditDate");editTitle=Find<TextBox>("EditTitle");editHour=Find<ComboBox>("EditHour");editMinute=Find<ComboBox>("EditMinute");editLocation=Find<TextBox>("EditLocation");editNotes=Find<TextBox>("EditNotes");editCategory=Find<ComboBox>("EditCategory");editRepeat=Find<ComboBox>("EditRepeat");editReminder=Find<ComboBox>("EditReminder");themeSelect=Find<ComboBox>("ThemeSelect");opacitySlider=Find<Slider>("OpacitySlider");opacityValue=Find<TextBlock>("OpacityValue");detailTitle=Find<TextBlock>("DetailTitle");detailStatus=Find<TextBlock>("DetailStatus");detailDateTime=Find<TextBlock>("DetailDateTime");detailCategoryRepeat=Find<TextBlock>("DetailCategoryRepeat");detailReminder=Find<TextBlock>("DetailReminder");detailLocation=Find<TextBlock>("DetailLocation");detailNotes=Find<TextBlock>("DetailNotes");agendaTab=Find<Button>("AgendaTab");todayTab=Find<Button>("TodayTab");calendarTab=Find<Button>("CalendarTab");completedTab=Find<Button>("CompletedTab");pinButton=Find<Button>("PinButton");Find<TextBlock>("DateText").Text=DateTime.Now.ToString("M月d日 dddd",CultureInfo.GetCultureInfo("zh-CN"));monthCalendar.SelectedDate=DateTime.Today;BuildTimes();}
 void BuildTimes(){editHour.Items.Add("无");for(int h=0;h<24;h++)editHour.Items.Add(h.ToString("00"));foreach(string m in new[]{"00","15","30","45"})editMinute.Items.Add(m);editHour.SelectedIndex=0;editMinute.SelectedIndex=0;editMinute.IsEnabled=false;editMinute.Opacity=.45;editHour.SelectionChanged+=delegate{editMinute.IsEnabled=editHour.SelectedIndex>0;editMinute.Opacity=editMinute.IsEnabled?1:.45;};}
 void LoadTasks(){loading=true;tasks=new ObservableCollection<TaskItem>();try{if(File.Exists(taskPath)){object raw=json.DeserializeObject(File.ReadAllText(taskPath,Encoding.UTF8));object[] a=raw as object[];if(a!=null)foreach(object x in a){TaskItem t=json.ConvertToType<TaskItem>(x);Normalize(t);tasks.Add(t);}else if(raw!=null){TaskItem t=json.ConvertToType<TaskItem>(raw);Normalize(t);tasks.Add(t);}}}catch(Exception ex){Log(ex);}foreach(TaskItem t in tasks)t.PropertyChanged+=Changed;loading=false;}
 static void Normalize(TaskItem t){if(String.IsNullOrEmpty(t.Id))t.Id=Guid.NewGuid().ToString();if(t.Title==null)t.Title="";if(String.IsNullOrEmpty(t.DueDate))t.DueDate=DateTime.Today.ToString("yyyy-MM-dd");if(String.IsNullOrEmpty(t.Category))t.Category="个人";if(String.IsNullOrEmpty(t.Repeat))t.Repeat="不重复";if(t.DueTime==null)t.DueTime="";if(t.Location==null)t.Location="";if(t.Notes==null)t.Notes="";if(t.Notified==null)t.Notified="";}
 void Bind(){view=CollectionViewSource.GetDefaultView(tasks);view.Filter=Filter;view.SortDescriptions.Add(new SortDescription("DueDate",ListSortDirection.Ascending));view.SortDescriptions.Add(new SortDescription("DueTime",ListSortDirection.Ascending));taskList.ItemsSource=view;}
 bool Filter(object o){TaskItem t=o as TaskItem;if(t==null)return false;string q=(searchBox.Text??"").Trim();bool s=q.Length==0||Has(t.Title,q)||Has(t.Notes,q)||Has(t.Location,q);bool state=mode=="Today"?!t.IsDone&&t.DueDate==DateTime.Today.ToString("yyyy-MM-dd"):mode=="Completed"?t.IsDone:!t.IsDone;return s&&state;}static bool Has(string s,string q){return(s??"").IndexOf(q,StringComparison.CurrentCultureIgnoreCase)>=0;}
 void Changed(object sender,PropertyChangedEventArgs e){if(loading||editing)return;TaskItem t=(TaskItem)sender;if(e.PropertyName=="IsDone"){if(t.IsDone)Next(t);if(!selfTest)SaveTasks();UpdateSummary();window.Dispatcher.BeginInvoke(new Action(delegate{view.Refresh();RefreshDay();UpdateSummary();}),DispatcherPriority.ContextIdle);}}
 void Next(TaskItem t){if(t.RecurrenceCreated||t.Repeat=="不重复")return;DateTime d;if(!DateTime.TryParseExact(t.DueDate,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out d))return;DateTime n;if(t.Repeat=="每天")n=d.AddDays(1);else if(t.Repeat=="每周")n=d.AddDays(7);else if(t.Repeat=="每月")n=d.AddMonths(1);else if(t.Repeat=="每年")n=d.AddYears(1);else return;loading=true;t.RecurrenceCreated=true;var c=new TaskItem{Title=t.Title,DueDate=n.ToString("yyyy-MM-dd"),DueTime=t.DueTime,Category=t.Category,Repeat=t.Repeat,Reminder=t.Reminder,Location=t.Location,Notes=t.Notes};c.PropertyChanged+=Changed;tasks.Add(c);loading=false;}
 void RunSelfTest(object s,EventArgs e){window.ContentRendered-=RunSelfTest;var p=new TaskItem{Title="__TEST__"};p.PropertyChanged+=Changed;tasks.Add(p);view.Refresh();ShowDetails(p);bool detail=detailsPanel.Visibility==Visibility.Visible&&detailTitle.Text==p.Title;HideOverlays();window.Dispatcher.BeginInvoke(new Action(delegate{p.IsDone=true;window.Dispatcher.BeginInvoke(new Action(delegate{bool a=!view.Cast<object>().Contains(p);mode="Completed";view.Refresh();bool b=view.Cast<object>().Contains(p);p.PropertyChanged-=Changed;tasks.Remove(p);Environment.ExitCode=a&&b&&detail?0:3;window.Close();}),DispatcherPriority.ApplicationIdle);}),DispatcherPriority.Background);}
 void Wire(){
  Find<Grid>("DragBar").MouseLeftButtonDown+=delegate(object s,MouseButtonEventArgs e){if(e.ClickCount==2)window.WindowState=window.WindowState==WindowState.Maximized?WindowState.Normal:WindowState.Maximized;else window.DragMove();};
  Find<Button>("CloseButton").Click+=delegate{window.Close();};Find<Button>("MinButton").Click+=delegate{window.WindowState=WindowState.Minimized;};pinButton.Click+=delegate{window.Topmost=!window.Topmost;pinButton.Content=window.Topmost?"◆":"◇";SaveSettings();};
  Find<Button>("NewButton").Click+=delegate{HideOverlays();ShowEditor(null);};Find<Button>("CancelEditor").Click+=delegate{editorPanel.Visibility=Visibility.Collapsed;};Find<Button>("SaveEditor").Click+=delegate{SaveEditor();};
  Find<Button>("SettingsButton").Click+=delegate{HideOverlays();settingsPanel.Visibility=Visibility.Visible;};Find<Button>("CloseSettings").Click+=delegate{settingsPanel.Visibility=Visibility.Collapsed;SaveSettings();};
  Find<Button>("CloseDetails").Click+=delegate{detailsPanel.Visibility=Visibility.Collapsed;};Find<Button>("DetailEdit").Click+=delegate{TaskItem t=detailsTask;detailsPanel.Visibility=Visibility.Collapsed;if(t!=null)ShowEditor(t);};
  themeSelect.SelectionChanged+=delegate{ApplyAppearance();QueueSettings();};opacitySlider.ValueChanged+=delegate{ApplyAppearance();QueueSettings();};
  searchBox.TextChanged+=delegate{searchHint.Visibility=searchBox.Text.Length==0?Visibility.Visible:Visibility.Collapsed;view.Refresh();UpdateSummary();};agendaTab.Click+=delegate{SetMode("Agenda");};todayTab.Click+=delegate{SetMode("Today");};calendarTab.Click+=delegate{SetMode("Calendar");};completedTab.Click+=delegate{SetMode("Completed");};monthCalendar.SelectedDatesChanged+=delegate{RefreshDay();};
  taskList.AddHandler(Button.ClickEvent,new RoutedEventHandler(TaskButton));taskList.PreviewMouseLeftButtonUp+=TaskCardClick;dayList.PreviewMouseLeftButtonUp+=DayCardClick;
  window.SourceInitialized+=delegate{((HwndSource)PresentationSource.FromVisual(window)).AddHook(WindowProc);};settingsTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(450)};settingsTimer.Tick+=delegate{settingsTimer.Stop();SaveSettings();};window.LocationChanged+=ScheduleSettings;window.SizeChanged+=ScheduleSettings;
  window.Closing+=delegate{if(settingsTimer!=null)settingsTimer.Stop();if(reminderTimer!=null)reminderTimer.Stop();if(notifyIcon!=null){notifyIcon.Visible=false;notifyIcon.Dispose();}if(!selfTest){SaveTasks();SaveSettings();}};
 }
 void TaskButton(object sender,RoutedEventArgs e){DependencyObject d=e.OriginalSource as DependencyObject;while(d!=null&&!(d is Button))d=VisualTreeHelper.GetParent(d);Button b=d as Button;TaskItem t=b==null?null:b.Tag as TaskItem;if(t==null)return;if(b.Name=="EditTask")ShowEditor(t);else if(b.Name=="DeleteTask"){t.PropertyChanged-=Changed;tasks.Remove(t);SaveTasks();view.Refresh();RefreshDay();UpdateSummary();}e.Handled=true;}
 void HideOverlays(){editorPanel.Visibility=Visibility.Collapsed;detailsPanel.Visibility=Visibility.Collapsed;settingsPanel.Visibility=Visibility.Collapsed;}
 static T Parent<T>(DependencyObject d)where T:DependencyObject{while(d!=null){T found=d as T;if(found!=null)return found;d=VisualTreeHelper.GetParent(d);}return null;}
 void TaskCardClick(object sender,MouseButtonEventArgs e){DependencyObject d=e.OriginalSource as DependencyObject;if(Parent<CheckBox>(d)!=null||Parent<Button>(d)!=null)return;ListBoxItem row=Parent<ListBoxItem>(d);TaskItem t=row==null?null:row.DataContext as TaskItem;if(t!=null)ShowDetails(t);}
 void DayCardClick(object sender,MouseButtonEventArgs e){ListBoxItem row=Parent<ListBoxItem>(e.OriginalSource as DependencyObject);DayEntry item=row==null?null:row.DataContext as DayEntry;if(item!=null&&item.Task!=null)ShowDetails(item.Task);}
 void ShowDetails(TaskItem t){detailsTask=t;HideOverlays();detailTitle.Text=t.Title;detailStatus.Text=t.IsDone?"✓ 已完成":"○ 待完成";DateTime d;string date=DateTime.TryParseExact(t.DueDate,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out d)?d.ToString("yyyy年M月d日 dddd",CultureInfo.GetCultureInfo("zh-CN")):t.DueDate;detailDateTime.Text=date+(String.IsNullOrEmpty(t.DueTime)?" · 全天":" · "+t.DueTime);detailCategoryRepeat.Text=t.Category+" · "+t.Repeat;detailReminder.Text=ReminderText(t.Reminder);detailLocation.Text=String.IsNullOrWhiteSpace(t.Location)?"未设置":t.Location;detailNotes.Text=String.IsNullOrWhiteSpace(t.Notes)?"无备注":t.Notes;detailsPanel.Visibility=Visibility.Visible;}
 static string ReminderText(int v){return v<0?"不提醒":v==0?"准时提醒":v==10?"提前 10 分钟":v==30?"提前 30 分钟":v==60?"提前 1 小时":v==1440?"提前 1 天":"提前 "+v+" 分钟";}
 void QueueSettings(){if(settingsTimer==null)return;settingsTimer.Stop();settingsTimer.Start();}
 void ApplyAppearance(){if(themeSelect==null||opacitySlider==null||themeSelect.SelectedIndex<0)return;bool dark=themeSelect.SelectedIndex==1;byte a=(byte)Math.Max(140,Math.Min(255,Math.Round(opacitySlider.Value*2.55)));opacityValue.Text=Math.Round(opacitySlider.Value)+"%";SetBrush("SurfaceBrush",dark,Color.FromArgb(a,24,28,36),Color.FromArgb(a,250,251,253));SetBrush("PanelBrush",dark,Color.FromArgb((byte)Math.Min(255,a+8),31,36,46),Color.FromArgb((byte)Math.Min(255,a+8),249,250,252));SetBrush("PopupSurfaceBrush",dark,Color.FromArgb((byte)Math.Min(255,a+18),32,37,47),Color.FromArgb((byte)Math.Min(255,a+18),252,253,255));SetBrush("InputBrush",dark,Color.FromArgb((byte)Math.Min(255,a+12),41,47,60),Color.FromArgb((byte)Math.Min(255,a+12),255,255,255));SetBrush("ItemBrush",dark,Color.FromArgb((byte)Math.Min(255,a+5),35,41,53),Color.FromArgb((byte)Math.Min(255,a+5),255,255,255));SetBrush("TextPrimaryBrush",dark,Color.FromRgb(239,242,247),Color.FromRgb(41,49,63));SetBrush("TextSecondaryBrush",dark,Color.FromRgb(171,180,194),Color.FromRgb(115,126,144));SetBrush("BorderBrush",dark,Color.FromRgb(70,79,96),Color.FromRgb(217,222,231));SetBrush("HoverBrush",dark,Color.FromRgb(55,63,80),Color.FromRgb(238,240,255));SetBrush("SelectedBrush",dark,Color.FromRgb(66,76,98),Color.FromRgb(223,228,255));}
 void SetBrush(string key,bool dark,Color darkColor,Color lightColor){window.Resources[key]=new SolidColorBrush(dark?darkColor:lightColor);}
 void SetMode(string v){mode=v;agendaPanel.Visibility=v=="Calendar"?Visibility.Collapsed:Visibility.Visible;calendarPanel.Visibility=v=="Calendar"?Visibility.Visible:Visibility.Collapsed;headerTitle.Text=v=="Calendar"?"月历":v=="Today"?"今天":v=="Completed"?"已完成":"我的日程";view.Refresh();RefreshDay();UpdateTabs();UpdateSummary();}
 void UpdateTabs(){SetTab(agendaTab,mode=="Agenda");SetTab(todayTab,mode=="Today");SetTab(calendarTab,mode=="Calendar");SetTab(completedTab,mode=="Completed");}static void SetTab(Button b,bool on){b.Background=on?new SolidColorBrush(Color.FromArgb(32,97,118,247)):Brushes.Transparent;b.Foreground=on?new SolidColorBrush((Color)ColorConverter.ConvertFromString("#4F63DA")):new SolidColorBrush((Color)ColorConverter.ConvertFromString("#687386"));}
 void ShowEditor(TaskItem t){editingTask=t;Find<TextBlock>("EditorHeading").Text=t==null?"新建日程":"编辑日程";editTitle.Text=t==null?"":t.Title;DateTime d;editDate.SelectedDate=t!=null&&DateTime.TryParseExact(t.DueDate,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out d)?d:(mode=="Calendar"&&monthCalendar.SelectedDate.HasValue?monthCalendar.SelectedDate.Value:DateTime.Today);SelectTime(t==null?"":t.DueTime);Select(editCategory,t==null?"个人":t.Category);Select(editRepeat,t==null?"不重复":t.Repeat);SelectReminder(t==null?-1:t.Reminder);editLocation.Text=t==null?"":t.Location;editNotes.Text=t==null?"":t.Notes;editorPanel.Visibility=Visibility.Visible;editTitle.Focus();}
 void SelectTime(string value){if(String.IsNullOrEmpty(value)){editHour.SelectedIndex=0;editMinute.SelectedIndex=0;return;}string[] p=value.Split(':');int h,m;if(p.Length!=2||!Int32.TryParse(p[0],out h)||!Int32.TryParse(p[1],out m)){editHour.SelectedIndex=0;editMinute.SelectedIndex=0;return;}editHour.SelectedIndex=Math.Max(1,Math.Min(24,h+1));editMinute.SelectedIndex=m>=45?3:m>=30?2:m>=15?1:0;}static void Select(ComboBox b,string v){for(int i=0;i<b.Items.Count;i++){ComboBoxItem x=(ComboBoxItem)b.Items[i];if(Convert.ToString(x.Content)==v){b.SelectedIndex=i;return;}}b.SelectedIndex=0;}void SelectReminder(int v){for(int i=0;i<editReminder.Items.Count;i++){ComboBoxItem x=(ComboBoxItem)editReminder.Items[i];if(Convert.ToString(x.Tag)==v.ToString()){editReminder.SelectedIndex=i;return;}}editReminder.SelectedIndex=0;}static string ComboText(ComboBox b){return Convert.ToString(((ComboBoxItem)b.SelectedItem).Content);}
 void SaveEditor(){string title=editTitle.Text.Trim();if(title.Length==0){MessageBox.Show("请填写日程标题。","桌面日程");return;}editing=true;TaskItem t=editingTask;if(t==null){t=new TaskItem();t.PropertyChanged+=Changed;tasks.Add(t);}t.Title=title;t.DueDate=(editDate.SelectedDate??DateTime.Today).ToString("yyyy-MM-dd");t.DueTime=editHour.SelectedIndex<=0?"":Convert.ToString(editHour.SelectedItem)+":"+Convert.ToString(editMinute.SelectedItem);t.Category=ComboText(editCategory);t.Repeat=ComboText(editRepeat);t.Reminder=Int32.Parse(Convert.ToString(((ComboBoxItem)editReminder.SelectedItem).Tag));t.Location=editLocation.Text.Trim();t.Notes=editNotes.Text.Trim();t.Notified="";t.RecurrenceCreated=false;editing=false;editorPanel.Visibility=Visibility.Collapsed;SaveTasks();view.Refresh();RefreshDay();UpdateSummary();}
 void RefreshDay(){if(dayList==null)return;var list=new ObservableCollection<DayEntry>();string day=(monthCalendar.SelectedDate??DateTime.Today).ToString("yyyy-MM-dd");foreach(TaskItem t in tasks.Where(x=>x.DueDate==day).OrderBy(x=>x.DueTime)){string p=t.IsDone?"✓ ":String.IsNullOrEmpty(t.DueTime)?"全天  ":t.DueTime+"  ";list.Add(new DayEntry{Display=p+t.Title+"  ·  "+t.Category,Task=t});}if(list.Count==0)list.Add(new DayEntry{Display="这一天没有日程"});dayList.ItemsSource=list;}
 void UpdateSummary(){int n=tasks.Count(x=>!x.IsDone);countText.Text=n+" 项待完成 · "+tasks.Count+" 项日程";if(mode!="Calendar"){emptyState.Visibility=view.IsEmpty?Visibility.Visible:Visibility.Collapsed;emptyTitle.Text=searchBox.Text.Length>0?"没有匹配的日程":mode=="Completed"?"没有已完成日程":"没有日程";}}
 void StartNotifications(){notifyIcon=new Forms.NotifyIcon{Icon=Drawing.SystemIcons.Information,Text="桌面日程",Visible=true};reminderTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(30)};reminderTimer.Tick+=delegate{DateTime now=DateTime.Now;foreach(TaskItem t in tasks.Where(x=>!x.IsDone&&x.Reminder>=0&&!String.IsNullOrEmpty(x.DueTime))){DateTime due;if(!DateTime.TryParseExact(t.DueDate+" "+t.DueTime,"yyyy-MM-dd HH:mm",CultureInfo.InvariantCulture,DateTimeStyles.None,out due))continue;string k=due.ToString("s");if(now>=due.AddMinutes(-t.Reminder)&&now<due.AddMinutes(1)&&t.Notified!=k){notifyIcon.BalloonTipTitle="日程提醒";notifyIcon.BalloonTipText=t.Title+Environment.NewLine+t.DueTime+"  "+t.Location;notifyIcon.ShowBalloonTip(8000);t.Notified=k;SaveTasks();}}};reminderTimer.Start();}
 void SaveTasks(){if(loading)return;try{string tmp=taskPath+".tmp";File.WriteAllText(tmp,json.Serialize(tasks.ToList()),new UTF8Encoding(false));if(File.Exists(taskPath)){try{File.Replace(tmp,taskPath,null);}catch{File.Copy(tmp,taskPath,true);File.Delete(tmp);}}else File.Move(tmp,taskPath);}catch(Exception ex){Log(ex);}}
 void LoadSettings(){try{WindowSettings s=File.Exists(settingsPath)?json.Deserialize<WindowSettings>(File.ReadAllText(settingsPath,Encoding.UTF8)):new WindowSettings();if(s.Width>=360)window.Width=s.Width;if(s.Height>=500)window.Height=s.Height;if(s.Left!=0||s.Top!=0){window.WindowStartupLocation=WindowStartupLocation.Manual;window.Left=s.Left;window.Top=s.Top;}window.Topmost=s.Topmost;pinButton=window.FindName("PinButton")as Button;if(pinButton!=null)pinButton.Content=window.Topmost?"◆":"◇";themeSelect.SelectedIndex=String.Equals(s.Theme,"Dark",StringComparison.OrdinalIgnoreCase)?1:0;opacitySlider.Value=s.Opacity>=55&&s.Opacity<=100?s.Opacity:94;ApplyAppearance();}catch(Exception ex){themeSelect.SelectedIndex=0;opacitySlider.Value=94;ApplyAppearance();Log(ex);}}
 void ScheduleSettings(object s,EventArgs e){if(settingsTimer==null||window.WindowState!=WindowState.Normal)return;settingsTimer.Stop();settingsTimer.Start();}void SaveSettings(){try{if(window.WindowState!=WindowState.Normal)return;File.WriteAllText(settingsPath,json.Serialize(new WindowSettings{Left=window.Left,Top=window.Top,Width=window.Width,Height=window.Height,Topmost=window.Topmost,Theme=themeSelect.SelectedIndex==1?"Dark":"Light",Opacity=opacitySlider.Value}),new UTF8Encoding(false));}catch(Exception ex){Log(ex);}}void Log(Exception ex){try{File.AppendAllText(logPath,DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss")+Environment.NewLine+ex+Environment.NewLine+Environment.NewLine,Encoding.UTF8);}catch{}}
 const int WM_NCHITTEST=0x84,HTLEFT=10,HTRIGHT=11,HTTOP=12,HTTOPLEFT=13,HTTOPRIGHT=14,HTBOTTOM=15,HTBOTTOMLEFT=16,HTBOTTOMRIGHT=17;IntPtr WindowProc(IntPtr h,int msg,IntPtr w,IntPtr l,ref bool handled){if(msg!=WM_NCHITTEST||window.WindowState==WindowState.Maximized)return IntPtr.Zero;int x=(short)(l.ToInt32()&65535),y=(short)((l.ToInt32()>>16)&65535);Point p=window.PointFromScreen(new Point(x,y));double z=8;bool a=p.X<z,b=p.X>window.ActualWidth-z,c=p.Y<z,d=p.Y>window.ActualHeight-z;int hit=a&&c?HTTOPLEFT:b&&c?HTTOPRIGHT:a&&d?HTBOTTOMLEFT:b&&d?HTBOTTOMRIGHT:a?HTLEFT:b?HTRIGHT:c?HTTOP:d?HTBOTTOM:0;if(hit!=0){handled=true;return new IntPtr(hit);}return IntPtr.Zero;}
}
internal static class Program
{
 [STAThread]static void Main(string[] args){bool test=args!=null&&args.Any(x=>String.Equals(x,"--self-test",StringComparison.OrdinalIgnoreCase));bool created;using(var m=new Mutex(true,@"Local\DesktopTodoWidget_Native_2",out created)){if(!created){MessageBox.Show("桌面日程已经在运行。","桌面日程");return;}try{new DesktopTodoApp(test).Run();}catch(Exception ex){string log=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"桌面日程-错误日志.txt");try{File.AppendAllText(log,DateTime.Now+Environment.NewLine+ex+Environment.NewLine,Encoding.UTF8);}catch{}MessageBox.Show("程序启动失败，详情见错误日志。","桌面日程");}}}
}
